# Generated by Django 2.1 on 2019-02-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190214_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
