# Generated by Django 2.1.7 on 2019-04-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('api', '0005_auto_20190406_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='customuser_ptr',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_table',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
    ]
